config/routes.rb
Rails.application.routes.draw do
  root 'beers#index'
  resources 'beers', only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :turbo_frame_request_variant

  private

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = PunkApi::Client.new.beers(beer_name: params[:query], per_page: 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.erb
<%= turbo_frame_tag "beer_#{beer.id}" do %>
  <div class="col">
    <div class="card h-100">
      <div class="row">
        <div class="col-md-4">
          <img
            src="<%= beer.image_url %>"
            alt="Trendy Pants and Shoes"
            class="img-fluid rounded-start"
            />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= beer.name %></h5>
            <p class="card-text">
              <%= beer.description %>
            </p>
            <p class="card-text">
              <small class="text-muted">First brewed <%= beer.first_brewed %></small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/beers/index.html+turbo_frame.erb
<%= turbo_frame_tag "beers" do %>
  <%= render partial: "beer", collection: @beers %>
<% end %>

app/views/beers/index.html.erb
<div class="container px-4 py-5" id="custom-cards">
  <h2 class="pb-2 border-bottom">Beers</h2>

  <div class="form-outline">
  <%= form_with(url: beers_path, method: :get, data: { controller: "search-form", turbo_frame: "beers", turbo_action: "advance" }) do |form| %>
      <%= form.text_field :query, placeholder: "Type beer name", data: { action: "input->search-form#search"} %>
    <% end %>
  </div>
  <br>
  <div class="row row-cols-2 row-cols-md-1 g-4">
    <%= turbo_frame_tag "beers" do %>
      <%= render partial: "beer", collection: @beers %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_load_more.html.erb
<% page ||= page || 1 %>>
<% url ||= url_for(request.params.merge(format: :turbo_stream, page: page)) %>
<div id="load_more">
  <%= turbo_frame_tag "load_more", src: url, loading: :lazy %>
</div>